### PR TITLE
Update logo

### PR DESCRIPTION
**Pull request by YoungFellow-le**
I spoke to @cstayyab about this, and he said that he will change the logo when he is free. But he seems busy, so I changed it myself.
I also changed the dashboard icon to one that is different from the WALC logo.

I also edited the `Readme.md`.

### CODE REVIEW

**Review by YoungFellow-le — COMMENTED** [review]
The removal of the code was an accident, I fixed it in the next commit.
Also, the commit message was meant to be: "Change dashboard icon (fix typo **No.2**)", It has nothing to do with #2

**Comment by Zzombiee2361** [comment]
Hmm, I've been thinking about changing the logo for a while, cause it looks so damn bad as a tiny icon. I'd avoid putting the whole tux in the logo, but idk what else to put there. Maybe just the tux head?

As for the dashboard icon, I feel it's fine to use the app icon so it's clear that it's a WALC specific button. Also remember that it's a dashboard, a cog icon give me the impression that it's a settings button (dashboard has more than settings).

**Comment by Zzombiee2361** [comment]
Maybe change the app icon to the one used by [WAClient](https://github.com/WAClient) instead?

**Comment by YoungFellow-le** [comment]
Sorry for the late reply.
As for the logo, this is what I came up with:
logo360x360

>As for the dashboard icon, I feel it's fine to use the app icon so it's clear that it's a WALC specific button.

In short, when I click on the WALC logo, I expect WhatsApp web to show up, nothing else. That's why I changed the dashboard icon to a cog (I got my mum's opinion, and she agreed). However,
>Also remember that it's a dashboard

I fully agree with you, so I made a new icon that represents WALC, but is different from the logo itself:
**Either:**

**OR:**


Sample1
**VS**
Sample2

I think the white one is better.

>Maybe change the app icon to the one used by [WAClient](https://github.com/WAClient) instead?

I made that icon when I was a noob at graphic design 😂. Trust me, It looks awful.

**Comment by Zzombiee2361** [comment]
Nice! That logo looks good!

The shadow on the second icon looks off tbh. I prefer the first dashboard icon. But you'd have to invert the color of the icon on dark mode

**Comment by YoungFellow-le** [comment]
So shall I use the first or the second one?
It's your call.
Maybe we can invert the icon in `observeTheme()`?

**Comment by YoungFellow-le** [comment]
I just need to test the logo a few times with the unread badge so I can tweek the size so it fits the circle. Then I'll commit.

**Comment by YoungFellow-le** [comment]
After we're done with the logo, I think you should release v1.0 after I finish publishing it to the AUR, and you finish #189

**Comment by Zzombiee2361** [comment]
Yes, use the second one and invert the color on dark mode.

> I think you should release v1.0
Yes, after what you said and the flatpak version

**Comment by YoungFellow-le** [comment]
Excellent

**Comment by YoungFellow-le** [comment]
How would I check that dark theme is on 😅? 
I don't think it's:
```js
if (observeTheme() == true) {
    // invert the colors
}

**Comment by YoungFellow-le** [comment]
I have to say, your logo looks great!
However, for the dashboard, it would be better if it was already part of the original logo.
And if your talking about it being the main WALC logo, then the problem is that it won't be recognisable because it's too small.

**Comment by YoungFellow-le** [comment]
@Zzombiee2361 
>Yes, use the second one and invert the color on dark mode.

I was thinking, if I add the invert command, it won't update until the dashboard button is initialized again, unless there's a way to listen out for the change in theme constantly.

So I thought about changing the dashboard icon's colour to one that would have enough contrast in light and dark mode.

**Comment by Zzombiee2361** [comment]
@reszkojr your logo looks cool! I'm not sure about the monochrome version though.

**Comment by YoungFellow-le** [comment]
Actually, I've got a better idea:

ezgif-2-8b1e140a27

This is just a preview, the actual icon won't have that horrible noise on the edge.

**Comment by Zzombiee2361** [comment]
I was gonna tell you how to listen to theme change, but I guess that works too.

The question now is, which icon to choose?

And after that I'm gonna need the SVG version and multiple sizes of the PNG image.

**Comment by YoungFellow-le** [comment]
> I was gonna tell you how to listen to theme change, but I guess that works too.

I'm listening.

And I'll get you the svg, that's fine

**Comment by YoungFellow-le** [comment]
But I think it's better if it stands out more anyway

**Comment by YoungFellow-le** [comment]
> The question now is, which icon to choose?

Do you mean: _What **logo** to choose?_ or _Which **dashboard icon** to choose?_

**Comment by Zzombiee2361** [comment]
```js
installDashboardIcon(icon) {
    const container = document.querySelector('#side header div:first-child');
    this.image = new Image(); // store as property so it could be modified
    // ...
}

setDashboardIcon(isDark) {
    this.image // I suggest toggling class here
}

observeTheme() {
    const isDark = document.body.classList.contains('dark');
    this.exec('setDarkTheme', isDark);
    this.setDashboardIcon(isDark);

    const observer = new MutationObserver(() => {
        const isDark = document.body.classList.contains('dark');
        this.exec('setDarkTheme', isDark);
        // any code here will run on theme change
        this.setDashboardIcon(isDark);
    });

    observer.observe(document.body, {
        attributes: true, 
        attributeFilter: ['class'],
        childList: false, 
        characterData: false
    });
}
```

something like that, but you need to add css to invert the color

**Comment by YoungFellow-le** [comment]
> something like that, but you need to add css to invert the color

I tried what you suggested @Zzombiee2361, and set the following as a test:
```js
setDashboardIconTheme(isDark) {

    if (isDark) {

	    console.log("DARK");
	
    } else {

	    console.log("LIGHT");

    }
}
```

And it only runs on startup, if I change the theme nothing happens.

**Comment by Zzombiee2361** [comment]
Why did you call the `observser.observe` method inside the `MutationObserver` callback 😆

**Comment by YoungFellow-le** [comment]
> Why did you call the observser.observe method inside the MutationObserver callback laughing

What are talking about @Zzombiee2361?
I told you it's working fine 😁

**Comment by YoungFellow-le** [comment]
I think my work is done here. 
I made the dashboard icon change colour at theme change, and added different size and vector logo files.
Please review this @Zzombiee2361.
Thank you very much.

**Comment by YoungFellow-le** [comment]
I'll try to finish the PKGBUILDs after Eid إن شاء الله

**Comment by Zzombiee2361** [comment]
Hey, sorry for the long response. There's Eid, so I haven't been able to work on this.

Can you make the logo sizes more standard? Please make 64x64, 128x128, 256x256, 512x512, (and optionally 1024x1024). Also please add the svg version of the dashboard icon. Everything else looks good to me.

**Comment by YoungFellow-le** [comment]
Give me a minute.

**Comment by YoungFellow-le** [comment]
Done!

**Comment by Zzombiee2361** [comment]
Uh, you missed the 256x256 size. Also please remove the non standard size, we don't need many sizes if there's already an svg version.

What's the difference between `logo.svg` and `logo_vector.svg`? It's kinda funny that you removed `logo.svg` last commit and add it back again now

**Comment by Zzombiee2361** [comment]
Alright I'll merge this for now

**Pull request merged**
